---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Copilot Dashboard
headerStyle: underlined

background:
  image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
  blur: sm
  saturate: 100
  brightness: 50
  opacity: 100
favicon: https://images.squarespace-cdn.com/content/659067c6deda3f6229908685/edb1cab3-0eca-4ab0-ad89-24babb0a37a1/fav+white.png?content-type=image%2Fpng
theme: dark
color: slate
useEqualHeights: true

iconStyle: theme
hideVersion: true
hideErrors: true
showStats: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true
logpath: /opt/homepage-prod-1/appdata/

fiveColumns: true
layout:
  Infrastructure and Data:
    icon: mdi-server-#FFFFFF
    style: column
  Management:
    icon: mdi-auto-fix-#FFFFFF
    style: column
  IoT and Smarthome:
    icon: mdi-home-#FFFFFF
    style: column
  Security and Identity:
    icon: mdi-shield-lock-#FFFFFF
    style: column

