---
networks:
  frontend:
    external: true
  backend:
    external: true
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.8.9
    container_name: homepage
    environment:
      PUID: $PUID
      PGID: $PGID
      LOG_LEVEL: debug
    ports:
      - 85:3000
    env_file: /opt/thinkstation/.env
    volumes:
      - /opt/thinkstation/appdata/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
    networks:
      - frontend
      - backend