---
version: '3.4'
services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:latest
    environment:
      PUID: $PUID
      PGID: $PGID
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: $DB_PORT
      DB_DATABASE: $DB_DATABASE
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
    volumes:
      - /opt/speedscale-prod-1/appdata/speedtest:/config
      - /opt/speedscale-prod-1/appdata/speedtest/ssl:/config/keys
    env_file: /opt/speedscale-prod-1/.env
    ports:
      - 8443:443
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - speedtest
  db:
    container_name: speedtest-db
    image: mariadb:10
    restart: always
    environment:
      MARIADB_DATABASE: $MARIADB_DATABASE
      MARIADB_USER: $MARIADB_USER
      MARIADB_PASSWORD: $MARIADB_PASSWORD
      MARIADB_RANDOM_ROOT_PASSWORD: $MARIADB_RANDOM_ROOT_PASSWORD
    volumes:
      - /opt/speedscale-prod-1/appdata/speedtest/db:/var/lib/mysql
    env_file: /opt/speedscale-prod-1/.env
    networks:
      - speedtest
networks:
  speedtest:
    external: true